# -*- coding: utf-8 -*-
"""ExcelCY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nqBLfkse-WhLsxFM_pninS0g1M2owuId

# **Excel to TRAIN SPACY**

https://spacy.io/universe/project/excelcy
"""

!pip install -q spacy==2.3.7

# Português
!python -m spacy download pt_core_news_sm
!python -m spacy download pt

!pip install excelcy

"""# **Como treinar Spacy NER**

fazer junto ou separado

arrumar o excel e passar o scrip frases para alimentar essse excel

# **TRAIN_DATA**
"""

# Import
from excelcy import ExcelCy
excelcy = ExcelCy()
# Como funciona antes do treinamento:
doc = excelcy.nlp('Bolsonaro é o presidente do Brasil')
print([(ent.label_, ent.text) for ent in doc.ents])

# Excelcy entra em ação para melhorar o treinamento via excel:
excelcy = ExcelCy.execute(file_path= '/content/test_data_01.xlsx')
# use the nlp object as per spaCy API
doc = excelcy.nlp('Bolsonaro é o presidente do Brasil')
# Vendo se o treinamento funcionou:
print([(ent.label_, ent.text) for ent in doc.ents])